import type { Product } from "@/types/product"

// Mock products data
export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Camiseta Dry-Fit Performance",
    description:
      "Camiseta de alta performance para treinos intensos. Tecnologia Dry-Fit que mantém o corpo seco durante os exercícios.",
    price: 89.9,
    oldPrice: 119.9,
    category: "Roupas Masculinas",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Camiseta",
    inventory: 45,
    isNew: true,
    installments: 3,
  },
  {
    id: "2",
    name: "Legging Compressão Feminina",
    description:
      "Legging de compressão para melhor suporte muscular durante os treinos. Material de alta elasticidade e durabilidade.",
    price: 129.9,
    category: "Roupas Femininas",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Legging",
    inventory: 30,
    isNew: true,
    installments: 4,
  },
  {
    id: "3",
    name: "Tênis de Corrida Impulse",
    description:
      "Tênis desenvolvido especialmente para corridas de longa distância. Amortecimento de alto impacto e design leve.",
    price: 299.9,
    oldPrice: 349.9,
    category: "Acessórios",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Tênis",
    inventory: 15,
    installments: 10,
  },
  {
    id: "4",
    name: "Garrafa Térmica 1L",
    description:
      "Garrafa térmica com capacidade para 1 litro. Mantém sua bebida gelada por até 24 horas ou quente por até 12 horas.",
    price: 59.9,
    category: "Acessórios",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Garrafa",
    inventory: 50,
    installments: 2,
  },
  {
    id: "5",
    name: "Luvas de Treino Premium",
    description:
      "Luvas para treino de musculação com proteção extra para as palmas das mãos. Evita calos e melhora a aderência.",
    price: 79.9,
    category: "Acessórios",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Luvas",
    inventory: 25,
    installments: 2,
  },
  {
    id: "6",
    name: "Shorts Masculino Flex",
    description: "Shorts leve e flexível para treinos diversos. Possui bolsos laterais e forro interno.",
    price: 69.9,
    category: "Roupas Masculinas",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Shorts",
    inventory: 40,
    installments: 2,
  },
  {
    id: "7",
    name: "Top Esportivo Support",
    description: "Top esportivo com suporte médio para diversos tipos de treino. Material respirável e confortável.",
    price: 79.9,
    oldPrice: 99.9,
    category: "Roupas Femininas",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Top",
    inventory: 35,
    installments: 2,
  },
  {
    id: "8",
    name: "Whey Protein 900g",
    description:
      "Suplemento proteico para auxiliar na recuperação muscular pós-treino. Contém 25g de proteína por dose.",
    price: 149.9,
    category: "Suplementos",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Whey",
    inventory: 20,
    isNew: true,
    installments: 5,
  },
  {
    id: "9",
    name: "Corda de Pular Profissional",
    description: "Corda de pular com rolamentos e cabos de aço revestidos. Ideal para treinos de alta intensidade.",
    price: 49.9,
    category: "Acessórios",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Corda",
    inventory: 30,
    installments: 1,
  },
  {
    id: "10",
    name: "Regata Feminina Dry",
    description: "Regata feminina com tecnologia de secagem rápida. Leve e confortável para diversos tipos de treino.",
    price: 59.9,
    category: "Roupas Femininas",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Regata",
    inventory: 25,
    installments: 2,
  },
  {
    id: "11",
    name: "Mochila Esportiva 25L",
    description:
      "Mochila esportiva com compartimentos específicos para roupas, calçados e acessórios. Capacidade de 25 litros.",
    price: 129.9,
    oldPrice: 159.9,
    category: "Acessórios",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Mochila",
    inventory: 15,
    installments: 4,
  },
  {
    id: "12",
    name: "Bermuda Térmica Compressão",
    description: "Bermuda térmica de compressão para suporte muscular. Ideal para corridas e treinos intensos.",
    price: 89.9,
    category: "Roupas Masculinas",
    imageUrl: "/placeholder.svg?height=400&width=300&text=Bermuda",
    inventory: 20,
    installments: 3,
  },
]

// Mock orders data
export const mockOrders = [
  {
    id: "ORD001",
    customer: {
      name: "João Silva",
      email: "joao.silva@example.com",
      phone: "(11) 98765-4321",
    },
    date: "2023-11-15T10:30:00",
    status: "Entregue",
    paymentMethod: "Cartão de Crédito",
    items: [
      {
        id: "1",
        name: "Camiseta Dry-Fit Performance",
        price: 89.9,
        quantity: 2,
      },
      {
        id: "5",
        name: "Luvas de Treino Premium",
        price: 79.9,
        quantity: 1,
      },
    ],
    shippingAddress: {
      street: "Rua das Flores",
      number: "123",
      complement: "Apto 45",
      city: "São Paulo",
      state: "SP",
      zipCode: "01234-567",
    },
    subtotal: 259.7,
    shipping: 15,
    discount: 0,
    total: 274.7,
  },
  {
    id: "ORD002",
    customer: {
      name: "Maria Oliveira",
      email: "maria.oliveira@example.com",
      phone: "(21) 98765-1234",
    },
    date: "2023-11-10T14:45:00",
    status: "Enviado",
    paymentMethod: "PIX",
    items: [
      {
        id: "2",
        name: "Legging Compressão Feminina",
        price: 129.9,
        quantity: 1,
      },
      {
        id: "7",
        name: "Top Esportivo Support",
        price: 79.9,
        quantity: 2,
      },
    ],
    shippingAddress: {
      street: "Avenida Brasil",
      number: "456",
      complement: "Bloco B",
      city: "Rio de Janeiro",
      state: "RJ",
      zipCode: "20000-123",
    },
    subtotal: 289.7,
    shipping: 15,
    discount: 28.97,
    total: 275.73,
  },
  {
    id: "ORD003",
    customer: {
      name: "Pedro Santos",
      email: "pedro.santos@example.com",
      phone: "(31) 99876-5432",
    },
    date: "2023-11-05T09:15:00",
    status: "Processando",
    paymentMethod: "Boleto",
    items: [
      {
        id: "8",
        name: "Whey Protein 900g",
        price: 149.9,
        quantity: 2,
      },
    ],
    shippingAddress: {
      street: "Rua das Palmeiras",
      number: "789",
      complement: "",
      city: "Belo Horizonte",
      state: "MG",
      zipCode: "30000-789",
    },
    subtotal: 299.8,
    shipping: 15,
    discount: 0,
    total: 314.8,
  },
  {
    id: "ORD004",
    customer: {
      name: "Ana Costa",
      email: "ana.costa@example.com",
      phone: "(41) 98765-9876",
    },
    date: "2023-11-01T16:20:00",
    status: "Pendente",
    paymentMethod: "Cartão de Crédito",
    items: [
      {
        id: "3",
        name: "Tênis de Corrida Impulse",
        price: 299.9,
        quantity: 1,
      },
      {
        id: "9",
        name: "Corda de Pular Profissional",
        price: 49.9,
        quantity: 1,
      },
    ],
    shippingAddress: {
      street: "Rua dos Pinheiros",
      number: "101",
      complement: "Casa",
      city: "Curitiba",
      state: "PR",
      zipCode: "80000-101",
    },
    subtotal: 349.8,
    shipping: 15,
    discount: 0,
    total: 364.8,
  },
  {
    id: "ORD005",
    customer: {
      name: "Lucas Ferreira",
      email: "lucas.ferreira@example.com",
      phone: "(51) 98888-7777",
    },
    date: "2023-10-28T11:10:00",
    status: "Cancelado",
    paymentMethod: "PIX",
    items: [
      {
        id: "11",
        name: "Mochila Esportiva 25L",
        price: 129.9,
        quantity: 1,
      },
    ],
    shippingAddress: {
      street: "Avenida dos Ipês",
      number: "222",
      complement: "",
      city: "Porto Alegre",
      state: "RS",
      zipCode: "90000-222",
    },
    subtotal: 129.9,
    shipping: 15,
    discount: 0,
    total: 144.9,
  },
]

// Mock promotions data
export const mockPromotions = [
  {
    id: "PROMO1",
    name: "Desconto de Boas-vindas",
    code: "BEMVINDO10",
    discountType: "percentage",
    discountValue: 10,
    startDate: new Date("2023-10-01"),
    endDate: new Date("2023-12-31"),
    isActive: true,
    minPurchase: 0,
  },
  {
    id: "PROMO2",
    name: "Frete Grátis",
    code: "FRETEGRATIS",
    discountType: "fixed",
    discountValue: 15,
    startDate: new Date("2023-11-01"),
    endDate: new Date("2023-11-30"),
    isActive: true,
    minPurchase: 200,
  },
  {
    id: "PROMO3",
    name: "Black Friday",
    code: "BLACK30",
    discountType: "percentage",
    discountValue: 30,
    startDate: new Date("2023-11-24"),
    endDate: new Date("2023-11-26"),
    isActive: true,
    minPurchase: 300,
  },
  {
    id: "PROMO4",
    name: "Desconto em Acessórios",
    code: "ACESSORIOS15",
    discountType: "percentage",
    discountValue: 15,
    startDate: new Date("2023-10-15"),
    endDate: new Date("2023-12-15"),
    isActive: false,
    minPurchase: 100,
  },
]
